# Generated by Django 5.1 on 2025-07-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_technologies'),
        ('api', '0003_technology_project_is_deployed_project_technologies'),
    ]

    operations = [
    ]
